# Generated by Django 3.2.5 on 2021-07-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=30, verbose_name='descrição'),
        ),
    ]
